# Generated by Django 4.2.4 on 2023-12-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emilio_salinas_Final_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_inscripcion', models.DateField()),
                ('hora_inscripcion', models.TimeField()),
                ('estado', models.CharField(choices=[('R', 'Reservado'), ('C', 'Completada'), ('A', 'Anulada'), ('N', 'No asisten')], max_length=1)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.AddField(
            model_name='inscrito',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emilio_salinas_Final_app.institucion'),
        ),
        migrations.AddIndex(
            model_name='inscrito',
            index=models.Index(fields=['nombre', '-fecha_inscripcion'], name='nombre_fecha_idx'),
        ),
    ]
