# Generated by Django 4.2.4 on 2023-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emilio_salinas_Final_app', '0002_inscrito_institucion_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='estado',
            field=models.CharField(choices=[('Res', 'Reservado'), ('Com', 'Completada'), ('Anu', 'Anulada'), ('NoA', 'No asisten')], max_length=3),
        ),
    ]
